### ISSUE TITLE
Help in installing it

### ISSUE THREAD

**Issue by leoheck** [tcr/vrml2svg#1]
Hi, I am trying to use your tool, but I am not able to install it since I don't know much about node.

I am receiving some errors. I would like to know which version of node it requires.

Thanks anyway.

**Comment by leoheck** [comment]
I couldn't install it, but I think I could at least run it. But it didn't do anything. Nothing is exported.
Does this tool work?

![image](https://user-images.githubusercontent.com/1277920/57421164-0a8b6a80-71e1-11e9-9900-750d6b456767.png)

**Comment by easyw** [comment]
hi @leoheck 
I think you are trying with a kicad wrl model...
would you try with a simple wrl model and then see if we can go further?
https://www.siggraph.org/special-projects/com97/vrmltest.wrl

**Comment by leoheck** [comment]
Hi @easyw!
Yes, I am running it with Kicad .wrl models.

Doesn't it work with Kicad models?
Do you know why?

I will try your model, thanks for sharing it.

**Comment by leoheck** [comment]
I got this now, but it might be something missing on my installation becasue I had to reinstall the OS yesterday.

```
➜ ./vrml2svg vrmltest.wrl lala.svg 
OBJ Shape
OBJ appearance Appearance
OBJ material Material
PROP diffuseColor [ 0.75, 0.5, '1.0' ]
PROP specularColor [ 0.7, 0.7, 0.8 ]
PROP shininess [ 0.1 ]
CLOSEOBJ }
CLOSEOBJ }
OBJ geometry Cylinder
PROP height [ 0.2 ]
PROP radius [ '3.0' ]
CLOSEOBJ }
CLOSEOBJ }
OBJ Shape
OBJ appearance Appearance
OBJ material Material
PROP diffuseColor [ 0.2, 0.5, 0.75 ]
PROP transparency [ '0.0' ]
CLOSEOBJ }
CLOSEOBJ }
OBJ geometry Sphere
PROP radius [ '1.0' ]
CLOSEOBJ }
CLOSEOBJ }
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'mrcolor'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/lheck/Downloads/vrml2svg/generate.js:2:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by leoheck** [comment]
What is clipper? I have some issues installing it.

```
make: *** [clipper.target.mk:101: Release/obj.target/clipper/clipperinit.o] Error 1
make: Leaving directory '/home/lheck/Downloads/vrml2svg/node_modules/clipper/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.0.0-13-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lheck/Downloads/vrml2svg/node_modules/clipper
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clipper@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clipper@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lheck/.npm/_logs/2019-05-10T14_53_19_919Z-debug.log
```

**Comment by leoheck** [comment]
Ah, it looks that my issue is the clipper. I was having build problems when installing it. So, the tool was not able to generate the view to export to svg. =/ The problem is that I have no idea on how to fix the clipper build/install.

**Comment by leoheck** [comment]
Do you have any idea on how to make clipper work?
